### ISSUE TITLE
Make OCV curve configurable via ThingSet

### ISSUE THREAD

**Issue by martinjaeger** [LibreSolar/bms-firmware#15]
This allows to better customize the BMS depending on the used cell.

**Comment by pasrom** [comment]
@martinjaeger, are you currently working on this issue? If not, I'd like to start on it. It seems like a good addition to our project.

**Comment by martinjaeger** [comment]
No, I'm not working on that right now and would appreciate any support.

I have added support for writing arrays via ThingSet in text mode a few days ago, which might be helpful for this. It just needs an update to the latest git SHA for the ThingSet SDK in the west.yml.

**Comment by pasrom** [comment]
@martinjaeger I have a follow-up question: Do you mean that each OCV curve should be configurable, or only when `CELL_TYPE_CUSTOM` is selected?

**Comment by martinjaeger** [comment]
That's a good question. Probably it would make sense to use the `_CUSTOM` type for that and keep the others as a sensible default if no detailed cell data is available.

We should probably also allow to adjust the corresponding SOC points array, so that the resolution can be increased at very low and high SOCs, where the gradient of the OCV curve is steeper and not so linear.

What do you think?

**Comment by pasrom** [comment]
> That's a good question. Probably it would make sense to use the `_CUSTOM` type for that and keep the others as a sensible default if no detailed cell data is available.

Agreed on using `_CUSTOM` type for specific cases and default types for general use.

> We should probably also allow to adjust the corresponding SOC points array, so that the resolution can be increased at very low and high SOCs, where the gradient of the OCV curve is steeper and not so linear.

Also in favor of adjusting the SOC points array for better resolution at extreme SOCs.
