### ISSUE TITLE
add timer for logging-output frequency

### ISSUE THREAD

**Issue by case06** [LibreSolar/bms-firmware#3]
The logging-output happens way more faster than it is necessary for this kind of application and therefore generates too much traffic, which also means a (little) waste of energy.  A timer should be added to the calls within main.cpp, so the user can define an appropriate period by settings.  As default value  i recommend a period of 10s .

**Comment by martinjaeger** [comment]
The logging output period is now configurable via ThingSet, so we can close this issue.
