### ISSUE TITLE
bq769x0: repeat read due to crc fail might read different bytes an might led to wrong data read

### ISSUE THREAD

**Issue by kfessel** [LibreSolar/bms-firmware#53]
line 140 will probably try reading a different byte after the crc check failed -> there might be wrong date

https://github.com/LibreSolar/bms-firmware/blob/aa2203aedb176e5c9566f8ba862edca976f1ea4c/drivers/bms_ic/bq769x0/bq769x0.c#L139-L150

you might want to extend the loop to include a reg-addr write before the read retry

**Comment by martinjaeger** [comment]
@kfessel Please see PR #55 for a fix.
