### ISSUE TITLE
I2C error

### ISSUE THREAD

**Issue by Ananyaaynana** [LibreSolar/bms-firmware#59]
Hardware used:
Using a custom board with the same I2C configuration as the 0.4v bms_c1 board. GPIO8 is SDA and GPIO9 is SCL.
![Screenshot from 2024-02-29 14-14-53](https://github.com/LibreSolar/bms-firmware/assets/131510581/e773d83b-f469-4c16-a718-2fa2216e3d26)

Description of the issue:
We are using the bms_c1 firmware(code for 0.3v BMS board) at this commit https://github.com/LibreSolar/bms-firmware/tree/cb89c75b74e85a036b7c6243424e31c68b3b3018. An app.overlay file that updates the I2C pins to match the I2C configuration of the 0.4v bms_c1 board.
A few modifications have been done to the BMS firmware such as recovery for overcurrent in charge and discharge, short circuit and current calibration. We want to test these modifications in the lab before pushing the code to the bms_firmware repository. 

When the firmware is flashed on the custom board getting this error:
![Screenshot from 2024-02-29 14-08-50](https://github.com/LibreSolar/bms-firmware/assets/131510581/71bd4460-da99-4fff-8929-9e1dfdc87915)

Probing test points 12 and 13 revealed no observable signal waveforms on SDA and SCL lines. 

app.overlay:
![Screenshot from 2024-02-29 14-57-59](https://github.com/LibreSolar/bms-firmware/assets/131510581/1d481e36-6dc7-406e-a9c3-e6b9b68cac92)

Impact:
Not able to execute the firmware with and without recovery modifications.

Zephyr version: v3.4
    commit: b7e659cdd3088609c1e0b9d7f925a811c006f6bd

**Comment by martinjaeger** [comment]
Did you also try if it works with most recent firmware commit in main? It contains several improvements. Maybe it solves your issue.

**Comment by martinjaeger** [comment]
Ok. The overlay looks correct. Did you make sure it's picked up by the build system? (see output at the beginning of `west build` command)

**Comment by Ananyaaynana** [comment]
![Screenshot from 2024-02-29 19-53-19](https://github.com/LibreSolar/bms-firmware/assets/131510581/ddd79800-4796-4b14-94f2-2c7b69312779)
Yes, it has picked the app.overlay file during the build.

**Comment by Ananyaaynana** [comment]
We tried to debug the issue but it was unsuccessful. So we are integrating the recovery modifications in the latest commit but we hit a few roadblocks. I will open another thread to explain the issue.
