### ISSUE TITLE
Warning when sending CAN data

### ISSUE THREAD

**Issue by Ananyaaynana** [LibreSolar/bms-firmware#66]
Testing the CAN interface on a custom board similar to 0.4v of BMS C1.
On the serial interface getting this as the output:
![Screenshot from 2024-03-16 14-19-53](https://github.com/LibreSolar/bms-firmware/assets/131510581/c674b783-0a04-46a0-8343-894b489484ec)
With a warning saying that unable to send CAN frame since it is too large. 
The output of the CAN software was this:
![image](https://github.com/LibreSolar/bms-firmware/assets/131510581/a98186f3-3d52-4df3-b756-5a8b4005d5db)
What can be the cause of this warning?

Firmware used: https://github.com/LibreSolar/bms-firmware/commit/50b5bc5bdae9ee7609a8f9edb43ee9fb062481d9

**Comment by martinjaeger** [comment]
That's because the voltages and temperatures don't fit into a single classical CAN frame. With the new ThingSet SDK packetized reports we send all data items in a multi-frame report to make this work. This was not yet included in the BMS firmware.

I have just merged #65 to include it. Please double-check if the warning has gone.

**Comment by Ananyaaynana** [comment]
Using commit: https://github.com/LibreSolar/bms-firmware/tree/187d315c7acb94628d0c467649940d386e8e79c5 at this commit the board is not able to send data through CAN. Output at the serial terminal:
![Screenshot from 2024-03-18 18-30-55](https://github.com/LibreSolar/bms-firmware/assets/131510581/fca32dc0-3240-4026-8ecb-607935f58646)
Data was not received in the CAN software dashboard.

Using commit: https://github.com/LibreSolar/bms-firmware/tree/50b5bc5bdae9ee7609a8f9edb43ee9fb062481d9 at this commit the board can send data through CAN. Output at the serial terminal:
![Screenshot from 2024-03-18 18-32-53](https://github.com/LibreSolar/bms-firmware/assets/131510581/306c57e2-4556-459e-859d-7eb73c89cefc)
Data received in the CAN software dashboard.

**Comment by martinjaeger** [comment]
Sorry, I forgot to enable one additional required Kconfig. Fixed in `main` now. See this commit: https://github.com/LibreSolar/bms-firmware/commit/fb078cc4b56179d12973b2ab40afc57f59054fa0

**Comment by Ananyaaynana** [comment]
Data received on the CAN software dashboard.
Output on serial terminal:
![Screenshot from 2024-03-19 19-33-49](https://github.com/LibreSolar/bms-firmware/assets/131510581/9f9ea976-29db-425e-8ae7-61911a9198b0)
Thank you for the help!
