### ISSUE TITLE
why alert_mask variable clear at function entry?

### ISSUE THREAD

**Issue by firepooh** [LibreSolar/bms-firmware#76]
hi~

may i question your bms code. 

why alert_mask variable clear at function entry?

after exe "ic_conf->alert_mask = 0" no more effect code 

any here something else hidden function?

https://github.com/LibreSolar/bms-firmware/blob/ce8b8766e49f4c986b83eab838e92be2ccf91f74/drivers/bms_ic/bq769x2/bq769x2.c#L414

**Comment by martinjaeger** [comment]
If the alert mask is not cleared, previously set flags will be maintained, which is not desired.

**Comment by Vadiml1024** [comment]
But this means that the alerts will be ALWAYS disabled as
expressions  xxx = !!(ic->data.alert_mask & ZZZ)   will be ALWAYS false

**Comment by martinjaeger** [comment]
Sorry for not taking a better look. You are right @firepooh, this is a bug. It's now fixed in #81.
