### ISSUE TITLE
Bug in the bq769x2_configure_alerts  function

### ISSUE THREAD

**Issue by Vadiml1024** [LibreSolar/bms-firmware#80]
https://github.com/LibreSolar/bms-firmware/blob/ad92b6acd5a589f23704c59ea708b19479d0f4ea/drivers/bms_ic/bq769x2/bq769x2.c#L407-L451

The statements like:
    ` ic_conf->alert_mask |= (ic_conf->alert_mask & BMS_ERR_CELL_UNDERVOLTAGE);
`
have no much sense.  
Probably the author wanted something else.

This probably relates to #76

**Comment by martinjaeger** [comment]
You are absolutely correct, thanks for reporting the bug @Vadiml1024.

Please take a look at PR #81 and let me know if you agree this fixes the bug.
